/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controladores.ControladorClientes;
import controladores.ControladorCotizaciones;
import controladores.ControladorEmpleados;
import controladores.ControladorLogin;
import controladores.ControladorPagos;
import controladores.ControladorPromociones;
import controladores.ControladorVehiculos;
import controladores.ControladorVentas;
import java.awt.Color;

/**
 *
 * @author Geraldine Acosta
 */
public class AdminPanel extends javax.swing.JFrame {

    ControladorEmpleados ctrlEmpleados;
    ControladorClientes ctrlClientes;
    ControladorVehiculos ctrlVehiculos;
    ControladorCotizaciones ctrlCotizaciones;
    ControladorVentas ctrlVentas;
    ControladorPagos ctrlPagos;
    ControladorPromociones ctrlPromociones;
    ControladorLogin login;

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel(ControladorLogin login, ControladorEmpleados ctrlEmpleados,
            ControladorClientes ctrlClientes,
            ControladorVehiculos ctrlVehiculos,
            ControladorCotizaciones ctrlCotizaciones,
            ControladorVentas ctrlVentas,
            ControladorPagos ctrlPagos,
            ControladorPromociones ctrlPromociones) {

        this.login = login;
        this.ctrlEmpleados = ctrlEmpleados;
        this.ctrlClientes = ctrlClientes;
        this.ctrlVehiculos = ctrlVehiculos;
        this.ctrlCotizaciones = ctrlCotizaciones;
        this.ctrlVentas = ctrlVentas;
        this.ctrlPagos = ctrlPagos;
        this.ctrlPromociones = ctrlPromociones;
        initComponents();

        getContentPane().setBackground(new Color(230, 240, 255));
        setLocationRelativeTo(null);

        b1.setBackground(new Color(100, 150, 255));
        b1.setForeground(Color.WHITE);
        b1.setFocusPainted(false);

        b2.setBackground(new Color(100, 150, 255));
        b2.setForeground(Color.WHITE);
        b2.setFocusPainted(false);

        b3.setBackground(new Color(100, 150, 255));
        b3.setForeground(Color.WHITE);
        b3.setFocusPainted(false);

        b4.setBackground(new Color(100, 150, 255));
        b4.setForeground(Color.WHITE);
        b4.setFocusPainted(false);

        b5.setBackground(new Color(100, 150, 255));
        b5.setForeground(Color.WHITE);
        b5.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel2.setText("LE DAMOS LA BIENVENIDA AL SISTEMA DE LA CONCECIONARIA");

        b1.setText("Gestionar Empleados");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("Generar Reportes");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("Gestionar Promociones");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("Gestionar Vehiculos");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("Cerrar Sesión");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        jLabel1.setText("MENÚ");

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel3.setText("Da CLICK para manejar los paneles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(b1)
                        .addGap(55, 55, 55)
                        .addComponent(b4)
                        .addGap(51, 51, 51)
                        .addComponent(b3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b5)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b4)
                    .addComponent(b3))
                .addGap(46, 46, 46)
                .addComponent(b2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(b5)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        GestionarEmpleadosPanel emp = new GestionarEmpleadosPanel(ctrlEmpleados);
        emp.setVisible(true);
        emp.setLocationRelativeTo(null);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed

    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        GestionarVehiculosPanel vehi = new GestionarVehiculosPanel(ctrlVehiculos);
        vehi.setVisible(true);
        vehi.setLocationRelativeTo(null);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        Login log = new Login(
                login,
                ctrlEmpleados,
                ctrlVehiculos,
                ctrlClientes,
                ctrlPromociones,
                ctrlCotizaciones,
                ctrlVentas,
                ctrlPagos
        );
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_b5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
