/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Administrador;
import clases.Empleado;
import clases.RolEmpleado;
import clases.Vendedor;
import controladores.ControladorClientes;
import controladores.ControladorCotizaciones;
import controladores.ControladorEmpleados;
import controladores.ControladorLogin;
import controladores.ControladorPagos;
import controladores.ControladorPromociones;
import controladores.ControladorVehiculos;
import controladores.ControladorVentas;
import java.awt.Color;

/**
 *
 * @author Geraldine Acosta
 */
public class Login extends javax.swing.JFrame {

    ControladorEmpleados ctrlEmpleados;
    ControladorClientes ctrlClientes;
    ControladorVehiculos ctrlVehiculos;
    ControladorCotizaciones ctrlCotizaciones;
    ControladorVentas ctrlVentas;
    ControladorPagos ctrlPagos;
    ControladorPromociones ctrlPromociones;
    ControladorLogin login;

    /**
     * Creates new form Login
     */
    public Login(ControladorLogin login, ControladorEmpleados ce,
            ControladorVehiculos cv,
            ControladorClientes cc,
            ControladorPromociones cp,
            ControladorCotizaciones ccot,
            ControladorVentas cven,
            ControladorPagos cpagos) {
        initComponents();

        this.login = login;
        this.ctrlEmpleados = ce;
        this.ctrlVehiculos = cv;
        this.ctrlClientes = cc;
        this.ctrlPromociones = cp;
        this.ctrlCotizaciones = ccot;
        this.ctrlVentas = cven;
        this.ctrlPagos = cpagos;

        getContentPane().setBackground(new Color(230, 240, 255));
        setLocationRelativeTo(null);
        loginButton.setBackground(new Color(100, 150, 255));
        loginButton.setForeground(Color.WHITE);
        loginButton.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel3.setText("Iniciar Sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(loginButton)))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(loginButton)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String usuario = usuarioField.getText();
        String password = new String(passwordField.getPassword());
        Empleado empleado = login.autenticar(usuario, password);

        AdminPanel admi = new AdminPanel(login, ctrlEmpleados, ctrlClientes, ctrlVehiculos, ctrlCotizaciones, ctrlVentas, ctrlPagos, ctrlPromociones);
        VendedorPanel vend = new VendedorPanel(login, empleado, ctrlEmpleados, ctrlClientes, ctrlVehiculos, ctrlCotizaciones, ctrlVentas, ctrlPagos, ctrlPromociones);

        if (empleado.getRolEmpleado().equals(RolEmpleado.ADMINISTRADOR)) {
            admi.setVisible(true);
            admi.setLocationRelativeTo(null);
            this.dispose();
        } else if (empleado.getRolEmpleado().equals(RolEmpleado.VENDEDOR)) {
            vend.setVisible(true);
            vend.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables
}
