/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Comprobante;
import clases.Cotizacion;
import clases.EstadoVehiculo;
import clases.Venta;
import controladores.ControladorCotizaciones;
import controladores.ControladorVentas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristhiam Aponte
 */
public class RegistrarVentaPanel extends javax.swing.JFrame {

    ControladorCotizaciones ctrlCotizaciones;
    ControladorVentas ctrlVentas;

    private DefaultTableModel modelo;

    /**
     * Creates new form RegistrarVentaPanel
     */
    public RegistrarVentaPanel(ControladorCotizaciones ctrlCotizaciones, ControladorVentas ctrlVentas) {
        this.ctrlCotizaciones = ctrlCotizaciones;
        this.ctrlVentas = ctrlVentas;

        modelo = new DefaultTableModel();
        modelo.addColumn("Cliente");
        modelo.addColumn("Vehículo");
        modelo.addColumn("Modelo");
        modelo.addColumn("Precio Cot.");
        modelo.addColumn("Fecha Cot.");

        initComponents();

        getContentPane().setBackground(new Color(230, 240, 255));
        setLocationRelativeTo(null);
        
        jTable1.setModel(modelo);

        fechaField.setText("dd/mm/yyyy");

        listarCotizacionesActivas();
    }

    private void listarCotizacionesActivas() {
        modelo.setRowCount(0);
        for (Cotizacion c : ctrlCotizaciones.getCotizaciones()) {
            if (c.getVehiculo().getEstado() != EstadoVehiculo.VENDIDO) {
                Object[] row = {
                    c.getCliente().getNombres() + " " + c.getCliente().getApellidoPaterno(),
                    c.getVehiculo().getMarca(),
                    c.getVehiculo().getModelo(),
                    String.format("%.2f", c.getMontoTotal()),
                    c.getFecha()
                };
                modelo.addRow(row);
            }
        }
    }

    private void mostrarComprobante(String textoComprobante) {
        JTextArea textArea = new JTextArea(textoComprobante);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(450, 500));
        JOptionPane.showMessageDialog(this, scrollPane, "Comprobante de Venta", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        regresarButton = new javax.swing.JButton();
        ventaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel7.setText("Registrar Venta");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel4.setText("Fecha (dd/mm/yyyy):");

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        regresarButton.setBackground(new java.awt.Color(100, 150, 255));
        regresarButton.setForeground(new java.awt.Color(255, 255, 255));
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        ventaButton.setBackground(new java.awt.Color(100, 150, 255));
        ventaButton.setForeground(new java.awt.Color(255, 255, 255));
        ventaButton.setText("Registrar Venta y Generar Comprobante");
        ventaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regresarButton)
                                .addGap(156, 156, 156)
                                .addComponent(ventaButton)))
                        .addGap(0, 227, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(ventaButton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaButtonActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        String fechaVenta = fechaField.getText();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una cotización de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!fechaVenta.matches("\\d{2}/\\d{2}/\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cotizacion cotizacionSeleccionada = null;
        int rowIndex = 0;
        for (Cotizacion c : ctrlCotizaciones.getCotizaciones()) {
            if (c.getVehiculo().getEstado() != EstadoVehiculo.VENDIDO) {
                if (rowIndex == selectedRow) {
                    cotizacionSeleccionada = c;
                    break;
                }
                rowIndex++;
            }
        }

        if (cotizacionSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Error al identificar la cotización.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Venta nuevaVenta = ctrlVentas.registrarVenta(cotizacionSeleccionada, fechaVenta);

        if (nuevaVenta != null) {
            Comprobante comprobante = new Comprobante(nuevaVenta);
            String textoComprobante = comprobante.generarTextoComprobante();

            mostrarComprobante(textoComprobante);

            listarCotizacionesActivas();
            fechaField.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la venta. Verifique estado del vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ventaButtonActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton regresarButton;
    private javax.swing.JButton ventaButton;
    // End of variables declaration//GEN-END:variables
}
