/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.MetodoPago;
import clases.Pago;
import clases.Venta;
import controladores.ControladorPagos;
import controladores.ControladorVentas;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristopher Pulido
 */
public class RegistrarPagoPanel extends javax.swing.JFrame {

    ControladorVentas ctrlVentas;
    ControladorPagos ctrlPagos;

    private DefaultTableModel modelo;

    /**
     * Creates new form RegistrarPagoPanel
     */
    public RegistrarPagoPanel(ControladorVentas ctrlVentas, ControladorPagos ctrlPagos) {
        this.ctrlVentas = ctrlVentas;
        this.ctrlPagos = ctrlPagos;

        modelo = new DefaultTableModel();
        modelo.addColumn("Cliente");
        modelo.addColumn("Vehículo");
        modelo.addColumn("Total Venta");
        modelo.addColumn("Saldo Pendiente");

        initComponents();

        getContentPane().setBackground(new Color(230, 240, 255));
        setLocationRelativeTo(null);

        ventasTable.setModel(modelo);

        metodoComboBox.setModel(new DefaultComboBoxModel<>(MetodoPago.values()));

        ventasTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                actualizarLabelSeleccion();
            }
        });

        listarVentasConDeuda();
    }

    private void listarVentasConDeuda() {
        modelo.setRowCount(0);

        for (Venta v : ctrlVentas.getVentas()) {
            Pago pago = ctrlPagos.buscarPagoPorVenta(v);

            double saldo = (pago != null) ? pago.getSaldoPendiente() : v.getCotizacion().getMontoTotal();

            if (saldo > 0) {
                Object[] row = {
                    v.getCotizacion().getCliente().getNombres() + " " + v.getCotizacion().getCliente().getApellidoPaterno(),
                    v.getCotizacion().getVehiculo().getMarca() + " " + v.getCotizacion().getVehiculo().getModelo(),
                    String.format("%.2f", v.getCotizacion().getMontoTotal()),
                    String.format("%.2f", saldo)
                };
                modelo.addRow(row);
            }
        }
    }

    private void actualizarLabelSeleccion() {
        int fila = ventasTable.getSelectedRow();
        if (fila >= 0) {
            String saldo = modelo.getValueAt(fila, 3).toString();
            jLabel8.setText("Saldo pendiente: S/ " + saldo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        montoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        metodoComboBox = new javax.swing.JComboBox<>();
        regresarButton = new javax.swing.JButton();
        pagoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ventasTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel7.setText("Registrar Pago");

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel8.setText("Seleccione una venta en la tabla");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel4.setText("Monto a Abonar:");

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel1.setText("Método de Pago:");

        regresarButton.setBackground(new java.awt.Color(100, 150, 255));
        regresarButton.setForeground(new java.awt.Color(255, 255, 255));
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        pagoButton.setBackground(new java.awt.Color(100, 150, 255));
        pagoButton.setForeground(new java.awt.Color(255, 255, 255));
        pagoButton.setText("RegistrarPago");
        pagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoButtonActionPerformed(evt);
            }
        });

        ventasTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ventasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ventasTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(montoField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(metodoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(regresarButton)
                                .addGap(206, 206, 206)
                                .addComponent(pagoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel8)))
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(metodoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarButton)
                    .addComponent(pagoButton))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoButtonActionPerformed
        int selectedRow = ventasTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una venta de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String montoTexto = montoField.getText();

        if (montoTexto.isEmpty() || !montoTexto.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Venta ventaSeleccionada = null;
        int indiceFila = 0;

        for (Venta venta : ctrlVentas.getVentas()) {
            Pago pago = ctrlPagos.buscarPagoPorVenta(venta);
            double saldo = (pago != null) ? pago.getSaldoPendiente() : venta.getCotizacion().getMontoTotal();

            if (saldo > 0) {
                if (indiceFila == selectedRow) {
                    ventaSeleccionada = venta;
                    break;
                }
                indiceFila++;
            }
        }

        if (ventaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Error al identificar la venta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double monto = Double.parseDouble(montoTexto);
        MetodoPago metodo = (MetodoPago) metodoComboBox.getSelectedItem();

        Pago pagoExistente = ctrlPagos.buscarPagoPorVenta(ventaSeleccionada);
        boolean exito;

        if (pagoExistente == null) {
            exito = ctrlPagos.registrarPago(ventaSeleccionada, metodo, monto);
        } else {
            exito = ctrlPagos.registrarPagoParcial(ventaSeleccionada, monto);
        }

        if (exito) {
            JOptionPane.showMessageDialog(this, "Pago registrado exitosamente.");
            listarVentasConDeuda();
            montoField.setText("");
            jLabel8.setText("Seleccione una venta en la tabla");
        } else {
            JOptionPane.showMessageDialog(this, "Error: El monto supera la deuda pendiente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pagoButtonActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<MetodoPago> metodoComboBox;
    private javax.swing.JTextField montoField;
    private javax.swing.JButton pagoButton;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTable ventasTable;
    // End of variables declaration//GEN-END:variables
}
