/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controladores.ControladorEmpleados;
import controladores.ControladorVehiculos;
import controladores.ControladorVentas;
import controladores.Reportes;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Geraldine Acosta
 */
public class ReportesPanel extends javax.swing.JFrame {

    ControladorVehiculos ctrlVehiculos;
    ControladorVentas ctrlVentas;
    ControladorEmpleados ctrlEmpleados;

    /**
     * Creates new form ReportesPanel
     */
    public ReportesPanel(ControladorVehiculos ctrlVehiculos, ControladorVentas ctrlVentas, ControladorEmpleados ctrlEmpleados) {
        this.ctrlVehiculos = ctrlVehiculos;
        this.ctrlVentas = ctrlVentas;
        this.ctrlEmpleados = ctrlEmpleados;

        initComponents();

        getContentPane().setBackground(new Color(230, 240, 255));
        setLocationRelativeTo(null);

        jTextArea1.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        regresarButton = new javax.swing.JButton();
        reporteIngresosButton = new javax.swing.JButton();
        pagoButton1 = new javax.swing.JButton();
        pagoButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inicioField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        finalField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        regresarButton.setBackground(new java.awt.Color(100, 150, 255));
        regresarButton.setForeground(new java.awt.Color(255, 255, 255));
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        reporteIngresosButton.setBackground(new java.awt.Color(100, 150, 255));
        reporteIngresosButton.setForeground(new java.awt.Color(255, 255, 255));
        reporteIngresosButton.setText("Reporte Ingresos Totales");
        reporteIngresosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteIngresosButtonActionPerformed(evt);
            }
        });

        pagoButton1.setBackground(new java.awt.Color(100, 150, 255));
        pagoButton1.setForeground(new java.awt.Color(255, 255, 255));
        pagoButton1.setText("Reporte de Vehiculos");
        pagoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoButton1ActionPerformed(evt);
            }
        });

        pagoButton2.setBackground(new java.awt.Color(100, 150, 255));
        pagoButton2.setForeground(new java.awt.Color(255, 255, 255));
        pagoButton2.setText("Reporte Ventas por Vendedor");
        pagoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel7.setText("Selecciona un Reporte");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel4.setText("Fecha inicio:");

        inicioField.setText("dd/mm/yyyy");

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel5.setText("Fecha Fin::");

        finalField.setText("dd/mm/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(regresarButton)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(inicioField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(finalField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagoButton2)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(pagoButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reporteIngresosButton)
                        .addGap(230, 230, 230))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inicioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(finalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagoButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagoButton1)
                    .addComponent(reporteIngresosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regresarButton)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reporteIngresosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteIngresosButtonActionPerformed
        String texto = Reportes.reporteIngresosTotales(ctrlVentas);
        jTextArea1.setText(texto);
    }//GEN-LAST:event_reporteIngresosButtonActionPerformed

    private void pagoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoButton1ActionPerformed
        String texto = Reportes.reporteDeVehiculos(ctrlVehiculos);
        jTextArea1.setText(texto);
    }//GEN-LAST:event_pagoButton1ActionPerformed

    private void pagoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoButton2ActionPerformed
        String fechaInicio = inicioField.getText();
        String fechaFin = finalField.getText();

        if (fechaInicio.isEmpty() || fechaFin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese ambas fechas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!fechaInicio.matches("\\d{2}/\\d{2}/\\d{4}") || !fechaFin.matches("\\d{2}/\\d{2}/\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Formato fecha: dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String texto = Reportes.reporteVentasPorVendedor(ctrlVentas, ctrlEmpleados, fechaInicio, fechaFin);
        jTextArea1.setText(texto);
    }//GEN-LAST:event_pagoButton2ActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField finalField;
    private javax.swing.JTextField inicioField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pagoButton1;
    private javax.swing.JButton pagoButton2;
    private javax.swing.JButton regresarButton;
    private javax.swing.JButton reporteIngresosButton;
    // End of variables declaration//GEN-END:variables
}
